# Generated by Django 4.0.5 on 2022-06-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_neighbourhood_options_neighbourhood_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='date',
        ),
    ]
